name: Java CI with Maven

on:
  push:
    branches:
      - main  # Esto ejecutará los tests cuando se haga un push a la rama main
  pull_request:
    branches:
      - main  # Esto ejecutará los tests cuando se haga un PR hacia la rama main

jobs:
  build:
    runs-on: ubuntu-latest  # Usamos Ubuntu como entorno de ejecución

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Clonamos el código desde GitHub

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Configura el JDK 11

      - name: Build with Maven
        run: mvn clean install  # Compila el proyecto con Maven

      - name: Run tests
        run: mvn test  # Ejecuta los tests automáticamente
